/// Shared skill labels for freelancer signup, mission posting, and marketplace filters.
/// Keep labels stable so matching works across app and API.
const int kMaxFreelancerSkills = 7;
const int kMaxMissionRequiredSkills = 8;

const List<String> kJobSkillsCatalog = [
  // — Développement & logiciel
  'Flutter',
  'Dart',
  'React',
  'Vue.js',
  'Angular',
  'Next.js',
  'Node.js',
  'Express.js',
  'Python',
  'Django',
  'FastAPI',
  'Java',
  'Spring Boot',
  'C#',
  '.NET',
  'PHP',
  'Laravel',
  'Symfony',
  'Ruby on Rails',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'Android natif',
  'iOS natif',
  'React Native',
  'API REST',
  'GraphQL',
  'Microservices',
  'DevOps',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'Elasticsearch',
  'Cybersécurité',
  'Tests QA',
  'Automatisation',

  // — Design & création
  'UI/UX Design',
  'Figma',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Maquettes web',
  'Design mobile',
  'Identité visuelle',
  'Logo & branding',
  'Motion design',
  'Montage vidéo',

  // — Marketing & contenu
  'Marketing digital',
  'SEO / SEM',
  'Réseaux sociaux',
  'Copywriting',
  'Rédaction web',
  'Traduction',
  'Community management',
  'Email marketing',

  // — Business & autres domaines
  'Gestion de projet',
  'Product Owner',
  'Analyse de données',
  'Excel / Tableaux',
  'Power BI',
  'Comptabilité',
  'Juridique / rédaction contrats',
  'Ressources humaines',
  'Assistant virtuel',
  'Service client',
  'Formation / Coaching',
  'Photographie',
  'Architecture d’intérieur',
  'Ingénierie (études)',
];
